server:
  port: 8092
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.118.254
auth:
  jwt:
    publicKeyPath: E:\\IDEA\\myGmall\\tmp\\rsa.pub
    expire: 25092000
    cookieName: GMALL_TOKEN
    userKeyName: USER_KEY
  rabbitmq:
    host: 192.168.118.254
    username: admin
    password: admin
    virtual-host: /admin

alipay:
  app_id: 2016101200666477
  notify_url: http://9glldacce2.52http.net/api/order/pay/alipay/success # 域名是哲西云提供的域名，路径是订单支付成功回调的路径
  return_url: http://localhost:2000/pay/success.html
  sign_type: RSA2
  charset: utf-8
  gatewayUrl: https://openapi.alipaydev.com/gateway.do