server:
  port: 8090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: 192.168.118.254
auth:
  jwt:
    publicKeyPath: E:\\IDEA\\myGmall\\tmp\\rsa.pub
    expire: 25092000
    cookieName: GMALL_TOKEN
    userKeyName: USER_KEY